name: Build & Test

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: prepare
        run: |
             sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
             sudo apt update
             sudo apt install g++-10
             sudo apt install libboost-all-dev
      - name: configure
        env:
          CXX: g++-10
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build build
      - name: test
        run: |
             ./build/common/common_unit_test
             ./build/rstar/rstar_unit_test
             ./build/mrastar/mrastar_unit_test
