name: Build & Test

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build build --verbose
      - name: test
        run: |
             ./build/common/common_unit_test
             ./build/rstar/rstar_unit_test
